[package]
name = "crabd"
version = "0.1.0-beta.3"
authors = ["Sertan Canpolat <58915038+scnplt@users.noreply.github.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
bollard = "0.18.1"
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = {version = "1.44.2", features = ["full"]}
